// <auto-generated />
using System;
using GeradorDinamicoDeReceitas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeradorDinamicoDeReceitas.Migrations
{
    [DbContext(typeof(RecipeDbContext))]
    [Migration("20260803231812_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GeradorDinamicoDeReceitas.Models.Entities.RecipeHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestrictionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("History");
                });
#pragma warning restore 612, 618
        }
    }
}
